language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - NODE_VERSION=8
    - $MAVEN_CLI_OPTS="--batch-mode"
    - secure: ibngQYjt4KVLkj7YYtcSknED+eT621oOUq5j4r9IShV6KxJnn93sYQ/aRhtSOOnRom+nZsLvFvmeZO5OioyRnMICcMqSNmFyMnTPrmInCb8HrGuZ37RleWtXdjGWuMPMuMUPxEf3d/ir0wW8vaPDXF7gJGOx8pk7xu/Vv+exNIVStKQ/OiJsafCTKwfsU93h0TQdGUG4b/kIyEOTuHcsPHrM2R3XqFu2e28QUPk1pIjiKob7ZelzUWdNh+h/BgLMasWJ1bSmrLaDKrqh8JqkfgwM325a8f13k8pWC7AmUHtdFfoXUAnV5fpv++ZkkFqzGsKaYncGwr1XIsU4ggfMspo2p/xr9e9IykHNUW5ky2TI4ui6yhAm++irl9oDlKpisxoDeOEiyspKDAYyoKqZTqqspmjjBbKIYSwurRdn9U2VFaUnRLsYgSB3qIRH9EtCSPCGsvLlfjYJVLxr0G+IpOpLYeo4tdt2qI0yKotmWeP5h9hFx0rizzpBLdo4o48+hfcn+khIXUBaMlKawADTjR9l+zZoFcNsKat3Sg4rqktQn7RMy2qgjfe+ds/Pc5pF2Vq5qtRI+jiZZcZ0Vc1G6i7/OBiL0/ZUOzRC4+TBWOqCbUCKqi0OFula2lRTQf3qNOwBBV79mqQJRQZQ6YGO406i5AH7FRpeNuJ32ExT1xM=
    - secure: W2S7UJ4w2sWSTCpS3tHHslg0MhZsz68yjUQtoFy5I3dW9grdWEVWjeZyK+jLeW1jO9HVNxPZB2jWRRaiZkcgLbJk1VzK7NwClo9MSLtMHzVcO/4zxw2mKAH/E1UwXLLje+Pqhxjmz8ndZug0hjLhSnqpOB6UZxuM+961p3bXD/NrVZn9Cupu14MiPtsPPMRe5EFBoVPs9OdepJZKv0ojX9HReu2qqsP++sG3gYqBKgKjExP8Q/b+mjNrqTVqfHVMHV5iCLgtaxPCZW+1uEZOLSp3z1NvxyT6g1DXugDnZVsJTBHbBhS4yLCxexDlsfOJsZCMuGRpwhst6aCLwpXzfJ8tcDNItY2CVPeQecvA/dhgd6Cxh62DKcGaN9mQ/s0QATRrdnYzfVjQwk0V1PyH4Eb6QgKaiTVVfKfx3XvrsKILOSoZyCeab8bYpAKTgB7Bff/9UPNbn39q92stI2DSvpCRE4I0jLUD5D4fXQ0CJa2Ranv2ObCg3k/VU5gspwkd1owJD2nd5mhcJ1N/SxK1vRrRb0HqXYZq6hdrJT2J2bm3nfESvJU9/58Vd5LtRUdX9BLMSPu0sU0gg0F5puJRrCxmpJ241//V3OpBYCbBojjQipvF9ZnAJJTFqxvx6mvyJHhGwtoA6nkINJUe1PKxZPoPiySnYoOojTyBXukyAGk=
    - secure: PRA0kbCSJO1fzfJtPm/Bc1ihq4Wo55+IN3edcQKcanQ3sOq2WOlFmBne007tLAy1YIh1Q3MoGwQQ2y3qnxEBXba4K3JbZUMdM9OQed8WEIFBbBlrdbHAbT28thlYro5HI2dpgW3r3W9y1jz82RDzSRBey1V4YVyDFxnWpXy++WIKy2/FwzxfMdBRMZ7xWjj0m2Mc2LcYZ9isfe7CO2D47ksKALU3JSwNc2o57GaX1oxWnzvsjEYQe1uyqLlC6v6wNWxeVA1RN+kANJYw4Up6rIF82ntW2quoKk/NV04xjrj0Lgkmu0wdJF3cqqOMj3niZC+s6yBTkAq0LruSpltsT++TOScBpiYERwt5HQhSQPyyoN7WrytDMtHq9A6fMDeMK/o/iRFpC32pbWsugFgbehFhPUIA20FknvOWhQXd4RBUSCpc2lXy0v4L0RqJYwUUQj2w8KFNvdnz07sRT3nNyJmr0ee9DfWIVvF8AYeXYf88bb6lu4GGtof3/L6G77eJmYpAbuICyYawNtuju9fO9o/18DPATyEma+35I3zqRFSGozB62tgWu+a670qkELUfZoAcYVyhBL/MfflKGQ0GKKZLvCFhzc9HhLywRwrt1z2/YaO+XO1kRisPVtGAnTe7X/Ow71uJA2gELHRnKqxzWQseSHiBwVZjVuYDfushxOM=

install:
  - nvm install $NODE_VERSION

script:
  - nvm use $NODE_VERSION
  - ./mvnw $MAVEN_CLI_OPTS clean verify

deploy:
  - provider: releases
    api_key:
      secure: ocSKy4AwZrkPCUWZttbvFj9aF0q+1t00uJ7EV9pT3MSyuOlRWnL44JKsScTehZxNr0ZiDOX6kPQVsqCYVzdWkjTynlPgJ8dBNgSW5xQb3guEm1wNP06FhRUwzZVq13OjHoYMdRakSEZC8aMNCTCRAUGNpAid23TPuY7yx10e/RRGTgfcBOqZ4/Ltsx9tga6oVsHcOrd2ve4TbiTmj7SDe/b+g3plY/8KoZhx0/fXELXNuKvQYZ8zkgqmM5egnUvDAZkdQcFyHYgpQGa8fzsmYX1OmOvZLcxNsYTMGWFhxZuBYbWgKzrZsbIA/oKGa4+Y9QwvZC8A2wNge3/GWebDQXdB7jRKMZHxh6u026K2GIHyeMg+LQv6GH4PVQvfOYURHFsjuDwgwja9ItslSqSKkYg/1WtSquEFgZzWK2hgZSeGLS+yi5324IfyX06g99vHNOurmiQ8JZrirkrI+OH+RBRcS3PA0MIv6ZqqlveRClsr6MUvqN03rwqVX8fh3utJ6RmAZQ8UrapiWccJeiGbhyMUmrXQ8vXmj6vgfKF2cOlzscklYNDuihGxZfrbaR0JafEJGYJ+4nWebivvejlx0ipWgdo32QZUPcRdBKi+PuvZlP0yqIIYGFKDSFSxaWTEddTEY7/yuzJciUFuOL6eN7IOAsS52ZHUV7W1D0269P4=
    file_glob: true
    file: './target/navigation-bar*.jar'
    skip_cleanup: true
    on:
      tags: true
      repo: coffeenet/coffeenet-navigation-bar

  - provider: script
    script: openssl aes-256-cbc -K $encrypted_69ea10b618e5_key -iv $encrypted_69ea10b618e5_iv -in coffeenet.pgp.enc -out coffeenet.pgp -d &&
      gpg --fast-import coffeenet.pgp &&
      ./mvnw $MAVEN_CLI_OPTS deploy --settings ${TRAVIS_BUILD_DIR}/.travis.settings.xml -Prelease
    skip_cleanup: true
    on:
      tags: true
      repo: coffeenet/coffeenet-navigation-bar
